# The Sky Devotion library: one short devotion per entry, chosen by what the sky is doing.
# Written Oct. 6, 2026 for La Porte Weather Now. Scripture is the King James Version (public domain);
# build_library.py fills in each verse's exact text from two KJV sources and refuses to build if
# they disagree. The devotions never name a town, so the same library works anywhere.
#
# sky: which weather it fits (see SKIES in devotion/sky.js for how a day's sky is chosen).
ENTRIES = [
  # ---------- clear ----------
  ("clear", "Psalm 118:24",
   "Clear skies make it easy to see the day as a gift. The psalmist didn't wait for a perfect week to rejoice; he rejoiced in the day he was given. Name three good things before lunch, and thank God for each one."),
  ("clear", "Psalm 19:1",
   "A clear sky is a sermon without words. Every sunrise says the same thing: Someone made this, and made it beautiful. Step outside for one minute today, look up, and say thank you."),
  ("clear", "Lamentations 3:22-23",
   "This morning's light is new, and so is God's mercy. Yesterday's mistakes don't get the last word over today. Start fresh, and offer someone else the same fresh start."),
  ("clear", "Psalm 113:3",
   "On a clear day you can follow the sun's whole path, from first light to last. Praise fits all of it, the busy hours and the quiet ones. Pick one moment this evening to watch the light go down and give thanks."),
  ("clear", "2 Samuel 23:4",
   "David pictured a good leader as a morning without clouds: clear, warm, and good for growing things. That is how our words and work can land on the people around us. Be that kind of light for someone today."),
  ("clear", "Matthew 5:45",
   "The sun came up on everybody this morning without checking who deserved it. Jesus said that is how our Father loves, and how we should love too. Do something kind today for someone who can't pay you back."),
  ("clear", "Psalm 84:11",
   "The psalm calls God a sun and a shield: light to see by, and protection from what we can't see. Both are given, not earned. Walk in the light you have today, and trust Him with the rest."),
  ("clear", "James 1:17",
   "The sun crosses the sky and the shadows shift all day, but God doesn't change like that. Every good thing in your life comes from a steady, generous Father. Thank Him today for one good gift you usually take for granted."),
  # ---------- beautiful (sunny, mild, light wind) ----------
  ("beautiful", "Genesis 1:31",
   "Some days the weather is just right, and it's hard not to call it very good. God called His creation very good long before we did. Get outside today if you can, and enjoy what He made."),
  ("beautiful", "Psalm 104:24",
   "On a mild, bright day the earth's riches are easy to see: trees, birds, sky, neighbors out walking. The psalmist couldn't count them all. Take a walk and count a few of God's works yourself."),
  ("beautiful", "Psalm 16:6",
   "A beautiful day is a good reminder of the pleasant places God has given you: a home, a town, people who know your name. Gratitude grows when we say it out loud. Tell someone today what you love about where you live."),
  ("beautiful", "Psalm 145:9",
   "A gentle day feels like one of God's tender mercies, and the psalm says those mercies cover everything He made: people, animals, fields and lakes. None of it is left out. Show that same care today to a person or creature near you."),
  # ---------- gray ----------
  ("gray", "Job 37:21",
   "On a gray day the sun is still up there; we just can't see it. Elihu reminded Job that the light keeps shining behind the clouds until the wind clears them away. Keep going today, trusting that the light hasn't gone anywhere."),
  ("gray", "Psalm 42:11",
   "Gray skies can weigh on the heart, and the psalmist knew that feeling. He talked to his own soul and pointed it back to hope. If today feels heavy, tell God honestly, then call or text someone you trust."),
  ("gray", "Isaiah 50:10",
   "Isaiah wrote to people walking without much light, and he didn't tell them to pretend. He told them to trust and lean on God. On a dim day, lean a little harder, and let someone lean on you."),
  ("gray", "2 Corinthians 4:18",
   "Clouds remind us that what we can see isn't the whole story. Paul said the unseen things last longest: faith, hope and love. Spend a few minutes today on something that will outlast the weather."),
  ("gray", "Psalm 139:12",
   "A dark, cloudy day doesn't hide anything from God. He sees as clearly through the gray as through the sunshine. Whatever you're carrying today, He already sees it, and He cares."),
  ("gray", "Psalm 30:5",
   "Gray days pass, and so do hard seasons. The psalmist promises that joy comes in the morning, even when the night feels long. Hold on today, and help someone else hold on too."),
  ("gray", "Isaiah 60:1",
   "On a gray day, people notice anyone who brings a little light. Isaiah says God's glory has risen on His people so we can carry it to others. Be the bright spot in somebody's cloudy day."),
  # ---------- rain ----------
  ("rain", "Isaiah 55:10-11",
   "Rain never falls for nothing; it soaks in, and something grows. God says His word works the same way. Read a few verses today and let them soak in, even if you can't see the growth yet."),
  ("rain", "Hosea 6:3",
   "Hosea compares God's coming to the rain: faithful, refreshing, and right on time. Farmers wait for rain they can't make themselves. Wait on God today with that same kind of hope."),
  ("rain", "Psalm 147:8",
   "Today's clouds are part of a plan: rain for the earth, grass for the hills, food for the animals. God prepares good things before we know we need them. Thank Him for the rain, even if it changes your plans."),
  ("rain", "Zechariah 10:1",
   "Zechariah tells people to ask God for rain, about the most ordinary need there is. Nothing is too small to pray about. Bring God one ordinary need today and ask."),
  ("rain", "James 5:7",
   "Farmers can't hurry the rain; they plant, wait and trust. James says to wait for the Lord with that same patience. If something in your life is moving slowly, keep doing the next right thing today."),
  ("rain", "Acts 14:17",
   "Paul told a crowd that every rain shower is a witness to God's goodness. Rain fills rivers, fields and pantries. When you hear it on the roof today, let it remind you who provides."),
  ("rain", "Psalm 65:9",
   "The psalm says God visits the earth when He waters it. A rainy day is a visit, not an interruption. Slow down a little today and notice what the rain is feeding."),
  ("rain", "Matthew 5:45",
   "Rain falls on every yard on the street, the kind neighbors' and the grumpy ones'. Jesus said our Father gives like that, and asks us to love like that. Do a good turn today for someone you find hard to love."),
  # ---------- storm (thunderstorms in the forecast) ----------
  ("storm", "Mark 4:39",
   "Storms that frighten us don't frighten Jesus; His friends learned that on a lake in a sudden storm. When thunder roars, go indoors, and let His words settle your heart: Peace, be still."),
  ("storm", "Psalm 107:29",
   "Every storm has an end, and the psalm says God is the One who brings the calm. Thunder is loud, but it isn't the last word. Stay inside while it passes, and thank Him for the quiet afterward."),
  ("storm", "Psalm 29:3",
   "The psalmist heard thunder and thought of God's power and glory. Thunder reminds us how small we are and how great He is. When it rumbles, head indoors, and let it turn your heart to worship."),
  ("storm", "Isaiah 25:4",
   "Isaiah calls God a refuge from the storm, especially for the poor and the needy. Some neighbors have less shelter than others when the weather turns. Check today on someone who might need a ride, a call, or a safe place."),
  ("storm", "Matthew 7:24-25",
   "Jesus said a life built on His words still stands when the rain and wind hit. Storms test foundations, not paint jobs. Spend a few minutes today building on the rock: read, pray, and do what He says."),
  # ---------- severe (a Weather Service watch or warning for severe storms or tornadoes) ----------
  ("severe", "Proverbs 22:3",
   "When the Weather Service warns of dangerous storms, getting ready is wisdom, not fear. Proverbs praises the person who sees trouble coming and takes shelter. Know where you'll go, keep your phone charged, and check on a neighbor before it hits."),
  ("severe", "Psalm 46:1",
   "On a day with dangerous weather, God is a very present help, right here, not far off. Faith and safety go together. Take shelter the moment a warning comes, and pray for everyone in the storm's path."),
  ("severe", "Psalm 91:1-2",
   "Psalm 91 is a shelter you can take anywhere, even to a basement or an inside hallway. Trusting God and heeding warnings belong together. Go to your safe place when you're told, and say this psalm while you wait."),
  ("severe", "Isaiah 32:2",
   "Isaiah pictures people becoming shelter for one another. On a dangerous weather day you might be someone's hiding place: a ride, a basement, a phone call. Make sure your own family is safe, then be that for someone else."),
  # ---------- fog ----------
  ("fog", "1 Corinthians 13:12",
   "Fog shows how little we can see at a time, and Paul says that's true of life, too. We know in part, but God knows us fully. Drive slow, keep your low beams on, and trust Him with what you can't see yet."),
  ("fog", "James 4:14",
   "Morning fog is here, and then it's gone. James says our days are like that, which makes each one worth spending well. Do the kind thing today instead of saving it for later."),
  ("fog", "Isaiah 44:22",
   "When the sun burns off the fog, it leaves no trace. Isaiah says God clears away our sins like that. If something from the past is hanging over you, turn back to Him today; He has already made the way."),
  ("fog", "Psalm 119:105",
   "In fog you only need enough light for the next few steps. God's word works the same way: a lamp for your feet, not a floodlight for the whole road. Take the next faithful step today, and take it slowly."),
  # ---------- wind ----------
  ("wind", "John 3:8",
   "You can't see the wind, but you can see what it moves. Jesus said the Spirit works like that in people's lives. Watch today for where God is moving, and go along with it."),
  ("wind", "Ecclesiastes 11:4",
   "If we wait for perfect conditions, we'll never plant anything. Even a weather watcher has to admit the Teacher is right: get on with the work when the wind blows. Do the good thing you've been putting off."),
  ("wind", "Psalm 135:7",
   "The psalm pictures God bringing the wind out of His storehouses. Even a blustery day comes from His hand. Tie down what might blow away, and remember who holds it all."),
  ("wind", "1 Kings 19:12",
   "Elijah watched a mighty wind, an earthquake and a fire go by, but God spoke afterward in a still small voice. Loud days make it hard to hear Him. Find a quiet minute today, away from the noise, and listen."),
  ("wind", "Matthew 8:27",
   "The disciples marveled that even the wind obeyed Jesus. On a windy day that's worth remembering: the One who calms the wind knows your name. Bring Him whatever is blowing you around today."),
  # ---------- first frost of the season ----------
  ("first-frost", "Genesis 8:22",
   "The first frost of the season means the seasons are turning, just as God promised Noah they always would. His faithfulness shows up in every turn of the calendar. Bring in tender plants and pets tonight, and thank Him for the harvest that's been."),
  ("first-frost", "Psalm 147:16",
   "Frost on the grass is God's handiwork, scattered overnight like ashes. The first one of the season is a good nudge to get ready for winter. Check the furnace and the neighbors, and make sure outdoor animals have shelter and water that won't freeze."),
  # ---------- frost ----------
  ("frost", "Job 38:29",
   "God asked Job where the frost comes from, and Job had no answer. Some mornings quietly remind us that we didn't make the world. Look closely at the frost today, then thank the One who did."),
  ("frost", "Proverbs 12:10",
   "Frosty nights are hard on animals that live outside. Scripture says a good person looks after the life of their animals. Make sure pets and livestock have shelter, bedding and water that hasn't frozen."),
  ("frost", "Psalm 36:6",
   "On a frosty morning, God is still the One who keeps people and animals alive, and we get to share in that care. Cover the garden, bring the pets in, and keep an eye out for any creature that needs help."),
  # ---------- cold (bitter cold, or a cold-weather alert) ----------
  ("cold", "James 2:15-16",
   "James says warm words don't warm anybody. On a bitter cold day, faith looks like a coat, a ride, a hot meal, or a call to someone who's alone. Find one person who needs warmth today, and help."),
  ("cold", "Proverbs 31:21",
   "The woman in Proverbs wasn't afraid of winter because she had her household ready for it. Getting ready is a way of loving people. Check the coats, blankets and car kit today, and share the extras."),
  ("cold", "Matthew 25:35-36",
   "Jesus said that when we clothe and shelter people, we do it for Him. Cold days make that need easy to see. Give a coat, support a warming center, or visit someone who's shut in today."),
  ("cold", "Psalm 147:17-18",
   "The psalmist admits nobody can stand up to God's cold, then reminds us He also sends the thaw. Bitter cold doesn't last forever. Bundle up, keep trips outside short, and look forward to the melting."),
  # ---------- first snow of the season ----------
  ("first-snow", "Isaiah 1:18",
   "The first snow covers everything in clean white, and God says that's what His forgiveness does. No stain is too deep for Him. Come to Him today with anything you've been carrying."),
  ("first-snow", "Job 37:6",
   "God speaks, and the first snow falls. It's a good day to marvel like a child. Slow down on the roads, enjoy the view, and let the wonder turn into thanks."),
  # ---------- snow ----------
  ("snow", "Psalm 51:7",
   "David prayed to be made whiter than snow after his worst failure. Fresh snow is a picture of a fresh start. Ask God for one today, and give someone else one, too."),
  ("snow", "Isaiah 55:10-11",
   "Snow looks like it just sits there, but it melts slowly and feeds the ground for spring. God says His word works quietly like that. Read a little today and trust that it is doing its work."),
  ("snow", "Job 37:6-7",
   "Elihu said snow stops people's work so they can notice God's work. A snowy day slows everything down, and that isn't all bad. Rest a little, look out the window, and remember who sends the snow."),
  ("snow", "Psalm 46:10",
   "Snow makes the whole world quieter. It's a good day to be still and remember that God is in charge. Take a few quiet minutes with Him before you pick up the shovel."),
  ("snow", "Galatians 6:2",
   "Snow is heavy, and so are some neighbors' burdens. Shoveling a walk for someone older or sick is the law of Christ with a shovel in hand. Clear a path for someone today."),
  ("snow", "Isaiah 1:18",
   "Fresh snow covers every mark on the ground, and God says His forgiveness covers us like that. Nothing you bring Him is too dark to wash white. Talk to Him today about what you've been carrying."),
  # ---------- winter storm (a Weather Service winter storm, blizzard, ice storm or lake-effect snow warning) ----------
  ("winter-storm", "Proverbs 22:3",
   "A winter storm is coming, and getting ready is wisdom. Proverbs praises people who see trouble ahead and take cover. Stock up early, stay off the roads when you're told to, and check on neighbors who live alone."),
  ("winter-storm", "Isaiah 32:2",
   "Isaiah pictures people as shelter for one another, a hiding place from the wind. In a winter storm you might be that shelter: a warm room, a shoveled walk, a phone call. Keep your own family safe first, then look around."),
  ("winter-storm", "Psalm 4:8",
   "When a winter storm closes the roads, home becomes a shelter. The psalmist could sleep in peace because God kept him safe. Stay put if you can, keep warm, and rest in Him tonight."),
  # ---------- ice (freezing rain, freezing drizzle or sleet) ----------
  ("ice", "Psalm 147:17",
   "Ice is beautiful and dangerous at the same time. The psalm reminds us we can't stand against God's cold on our own. Walk carefully, drive slower, and offer a steady arm to someone who needs it."),
  ("ice", "Psalm 121:3",
   "On icy days every step needs care. The psalm promises that God watches over us and never sleeps. Take small steps, salt your neighbor's steps too, and trust the One who keeps you."),
  ("ice", "Job 37:10",
   "Job's friend said frost and ice come by the breath of God, freezing the waters fast. Even a frozen world is in His hands. Be patient with slow roads today, and patient with the people on them."),
  # ---------- heat ----------
  ("heat", "Psalm 121:5-6",
   "On a hot day shade is a gift, and the psalm says God Himself is our shade. Take care of your body; it's His, too. Drink water, rest in the shade, and check on older neighbors who may not have air conditioning."),
  ("heat", "Isaiah 4:6",
   "Isaiah promised a shelter from the heat. Cooling centers, shade trees and a cold glass of water are small pictures of that care. Share some shade today with a person or animal who needs it."),
  ("heat", "Jeremiah 17:7-8",
   "A tree by the river stays green in the heat because its roots reach water. Trust in God works like that in hard seasons. Drink plenty of water today, and drink deeply from His word, too."),
  ("heat", "Matthew 10:42",
   "Jesus said even a cup of cold water given in His name matters. On a hot day, that cup may be the most loving thing you do. Hand a bottle of water to someone working outside, and put a bowl out for the animals."),
  # ---------- after the storm (yesterday stormy or rainy, today clearing) ----------
  ("after-storm", "Genesis 9:13",
   "After the flood, God set a rainbow in the sky as a promise to the whole earth. Storms come, but His promises stand. Look for signs of His faithfulness today, and thank Him for bringing you through."),
  ("after-storm", "Psalm 107:30",
   "The quiet after a storm is its own kind of gladness. The psalm says God brings us safely to harbor. If yesterday was rough, rest today, and help a neighbor clean up."),
  ("after-storm", "Romans 8:28",
   "Yesterday's storm is over, and cleanup days often show neighbors at their best. Paul says God works all things together for good for those who love Him. Pitch in where you can, and look for the good He's doing."),
  # ---------- flood (a Weather Service flood watch or warning) ----------
  ("flood", "Isaiah 43:2",
   "God promises to be with us in high water, and He also gave us sense to stay out of it. Never drive into a flooded road: turn around, don't drown. Pray for anyone facing rising water today, and keep your family on high ground."),
  ("flood", "Psalm 93:4",
   "Rivers rise and roar, but God is mightier than any flood. That truth gives us peace, not permission to take chances. Stay away from fast water today, and trust Him with what you can't control."),
  ("flood", "Psalm 29:10",
   "Even over a flood, God is on His throne. Floods are frightening, but they are not in charge. Follow the official warnings, help neighbors move things to higher ground, and rest in the King who reigns."),
]
